export const PERSONALCARDDATA = 'PERSONALCARDDATA';
export const PERSONALCARDDATACOMPLETE = 'PERSONALCARDDATACOMPLETE';
export const BUSINESSCARDDATA = 'BUSINESSCARDDATA';
export const BUSINESSCARDDATACOMPLTE = 'BUSINESSCARDDATACOMPLTE';
export const USERDATA = 'USERDATA';
