module.exports = {
    PHONE_NUMBER_ERROR: "Phone number can't be empty.",
    PASSWORD_ERROR: "Password can't be empty",
    MATCH_ERROR: "Password do not Match",
    CODE_ERROR: "Code can't be Empty",
    CREDIANTIAL_ERROR: "Invalid Crediantial",
    MATCH_PASSWORD: "Password does not match",
    EMPTY_NAME: "Name can't be Empty",
    EMPTY_OCCUPATION: "Occupation can't be Empty",
    EMPTY_PHONE: "Phone Number can't be Empty",
    EMPTY_EMAIL: "EMail can't be Empty",
    EMPTY_BIRTHDAY: "Birthday can't be Empty",
    EMPTY_ADDRESS: "Address can't be Empty",
    EMPTY_CITY: "City can't be Empty",
    EMPTY_COUNTRY: "COuntry can't be Empty",
    EMPTY_MESSAGE: "Message can't be Empty",
    EMPTY_QRCODE: "QR Code can't be Empty",
    EMPTY_HOBBIES: "Hobbies can't be Empty",
    EMPTY_EDUCATION: "Education can't be Empty",
    EMPTY_INTERESTS: "Interests can't be Empty",
    EMPTY_ACHIVEMENT: "Achivements can't be Empty",
    EMPTY_PERSONALINFO: "Personal Info can't be Empty",
    EMPTY_SKILLS: "Skills can't be Empty",
    EMPTY_PORTFOLIO: "PortFolio can't be Empty",
    EMPTY_JOBHISTORY: "Job History can't be Empty",
    EMPTY_PRODUCT: "Product Shelving can't be Empty",
    EMPTY_SERVICES: "Services Offered can't be Empty",
    EMPTY_HOURLY: "Hourly Vage can't be Empty",
    EMPTY_BUSINESS: "Busines Industry can't be Empty",
    EMPTY_INCORPORATION: "Date of Incorporation can't be Empty",
    EMPTY_PORTFOLIO: "PortFolio can't be Empty",
    EMPTY_WEBSITE: "Company Website can't be Empty",
};
